# Generated by Django 4.2.3 on 2023-07-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_languages_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, to='profiles.profile', verbose_name='Following'),
        ),
    ]
