# Generated by Django 4.2.3 on 2023-07-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Designates whether images is viewed at the profile', verbose_name='Active'),
        ),
    ]
