# Generated by Django 4.2.3 on 2023-08-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_model_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previousexperience',
            options={'ordering': ('-create_at', '-update_at'), 'verbose_name': 'Previous Experience', 'verbose_name_plural': 'Previous Experiences'},
        ),
    ]
