# Generated by Django 4.2.3 on 2023-07-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Model'), (3, 'Director'), (4, 'Other')], default=1, null=True, verbose_name='Role'),
        ),
    ]
