# Generated by Django 4.2.3 on 2023-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bug Report'), (2, 'Performance Issue'), (3, 'User Interface (UI) Issue'), (4, 'Security Vulnerability'), (5, 'Compatibility Issue'), (6, 'Data Integrity Issue'), (7, 'Documentation Issue'), (8, 'Accessibility Issue'), (9, 'Hardware Problem'), (10, 'Network Connectivity Issue'), (11, 'Crash Report'), (12, 'Installation/Deployment Issue'), (13, 'Usability/UX Issue'), (14, 'Performance Degradation'), (15, 'Feature Request'), (16, 'Discrimination'), (17, 'Bullying'), (18, 'Poverty and Homelessness'), (19, 'Substance Abuse'), (20, 'Mental Health Issues'), (21, 'Domestic Violence'), (22, 'Human Trafficking'), (23, 'Environmental Concerns'), (24, 'Education Disparities'), (25, 'Healthcare Access'), (26, 'Gender Inequality'), (27, 'Racial Injustice'), (28, 'Immigration and Refugee Challenges'), (29, 'Child Abuse and Neglect'), (30, 'Privacy Concerns'), (31, 'Nudity Content'), (32, 'Other')], default=32, null=True, verbose_name='Type'),
        ),
    ]
