# Generated by Django 4.2.3 on 2023-08-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Response')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Report Response',
                'verbose_name_plural': 'Report Responses',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
    ]
