# Generated by Django 4.2.3 on 2023-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportresponse_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active'),
        ),
    ]
