# Generated by Django 4.2.3 on 2023-08-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportresponse',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.report', verbose_name='Report'),
        ),
    ]
