# Generated by Django 4.2.3 on 2023-08-08 20:56

import django.core.validators
from django.db import migrations, models
import reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_reportresponse_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[reports.validators.FileContentTypeValidator(['application/pdf', 'image/jpg', 'image/jpeg', 'image/png', 'image/gif']), django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif']), reports.validators.FileSizeValidator(size_limit=5)], verbose_name='Attachment'),
        ),
    ]
