# Generated by Django 4.2.3 on 2023-08-08 22:20

import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='report/attachments/', validators=[profiles.validators.FileContentTypeValidator(['application/pdf', 'image/jpg', 'image/jpeg', 'image/png', 'image/gif']), django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif']), profiles.validators.FileSizeValidator(size_limit=5)], verbose_name='Attachment'),
        ),
    ]
