# Generated by Django 4.2.3 on 2023-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='is_authorized',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Authorized'),
        ),
    ]
