# Generated by Django 4.2.3 on 2023-07-26 09:10

import accounts.models
import agencies.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('agencies', '0002_alter_agency_is_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('student', agencies.models.DirectorUserManager()),
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
