# Generated by Django 4.2.3 on 2023-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_following_profile_following_agencies_and_more'),
        ('agencies', '0003_directoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='following_agencies',
            field=models.ManyToManyField(blank=True, related_name='follower_agencies', to='agencies.agency', verbose_name='Following Agencies'),
        ),
        migrations.AddField(
            model_name='agency',
            name='following_models',
            field=models.ManyToManyField(blank=True, related_name='follower_models', to='profiles.profile', verbose_name='Following Models'),
        ),
    ]
