# Generated by Django 4.2.3 on 2023-07-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agency_following_agencies_agency_following_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Designates whether images is viewed at the profile', verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agencies.agency', verbose_name='Agency')),
            ],
            options={
                'verbose_name': 'Agency Image',
                'verbose_name_plural': 'Agency Images',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
    ]
