# Generated by Django 4.2.3 on 2023-08-08 22:20

from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_alter_agencyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agency/extra/', validators=[profiles.validators.FileSizeValidator(size_limit=5)], verbose_name='Image'),
        ),
    ]
