# Generated by Django 4.2.3 on 2023-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('image', models.ImageField(upload_to='members/', verbose_name='Image')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Active')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
    ]
